### ISSUE TITLE
GroupMaster : Mass Add Group Members : Not working if we select Users according to their Roles

### ISSUE THREAD

**Issue by 143stalin** [jhersh/GroupMaster#1]
Hi Jonathan,

When we select Mass Add Group Members and then if we add Users according to their Roles,then it is not working.Is there any fix for this ? Rest of the features work awesome !!

Regards,
Stalin

**Comment by jhersh** [comment]
Ahoy @143stalin, I don't develop on force.com anymore and this project has not been updated in 4 years. I am surprised it still does anything at all! Unfortunately I cannot post any GroupMaster updates to the appexchange, so any fix would just be local to this repo. My apologies. Pull requests are welcome.

**Comment by 143stalin** [comment]
Thanks Jonathan .
